# Generated by Django 6.0 on 2026-07-31 02:04

import apps.portal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre de la exhibición', max_length=100, verbose_name='Nombre de la exhibición')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripción de la exhibición', null=True, verbose_name='Descripción de la exhibición')),
                ('Fecha_exhibicion', models.DateField(help_text='Fecha de la exhibición', verbose_name='Fecha de la exhibición')),
                ('Fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de registro', verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre del producto', max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripción del producto', null=True, verbose_name='Descripción del producto')),
                ('Categoria', models.CharField(choices=[('Mueble', 'Mueble'), ('Arte', 'Arte'), ('Accesorio_decoracion', 'Accesorio de decoración')], help_text='Categoría de producto', max_length=50, verbose_name='Categoría de producto')),
                ('Autor', models.CharField(help_text='Autor o fabricante del producto', max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=8)),
                ('Disponible', models.BooleanField(blank=True, default=True, help_text='Disponible')),
                ('Fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de registro del usuario', verbose_name='Fecha de registro del usuario')),
                ('Fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to=apps.portal.models.ruta_foto)),
                ('Fecha_carga', models.DateField(auto_now_add=True, help_text='Fecha de la exhibición', verbose_name='Fecha de la exhibición')),
                ('Exhibicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portal.exhibicion')),
                ('Producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portal.producto')),
            ],
        ),
    ]
