# Generated by Django 6.0 on 2026-08-26 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='Producto',
        ),
        migrations.AddField(
            model_name='exhibicion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibiciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foto',
            name='Fecha_carga',
            field=models.DateField(auto_now_add=True, help_text='Fecha de carga de imagen', verbose_name='Fecha de carga de imagen'),
        ),
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre del producto', max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripción del producto', null=True, verbose_name='Descripción del producto')),
                ('Categoria', models.CharField(choices=[('pintura', 'Pinturas'), ('escultura', 'Escultura'), ('fotografia', 'Fotografía'), ('arte_autoctono', 'Arte autóctono')], help_text='Categoría de producto', max_length=50, verbose_name='Categoría de producto')),
                ('Autor', models.CharField(help_text='Autor o fabricante del producto', max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=8)),
                ('Disponible', models.BooleanField(blank=True, default=True, help_text='Disponible')),
                ('Fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de registro por usuario', verbose_name='Fecha de registro por usuario')),
                ('Fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arte_registrado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='Arte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portal.arte'),
        ),
        migrations.CreateModel(
            name='Decoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre del producto', max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripción del producto', null=True, verbose_name='Descripción del producto')),
                ('Categoria', models.CharField(choices=[('espejo', 'espejos'), ('lampara', 'lámparas'), ('metalisteria', 'Metalistería'), ('acabado_antique', 'Acabado antique'), ('vidrio_ceramica', 'Vidrio y cerámica'), ('tapete', 'Tapetes'), ('cojin', 'Cojines'), ('madera_tallada', 'Madera tallada (ebanistería)')], help_text='Categoría de producto', max_length=50, verbose_name='Categoría de producto')),
                ('Autor', models.CharField(help_text='Autor o fabricante del producto', max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=8)),
                ('Disponible', models.BooleanField(blank=True, default=True, help_text='Disponible')),
                ('Fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de registro por usuario', verbose_name='Fecha de registro por usuario')),
                ('Fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_decoracion_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='Decoracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portal.decoracion'),
        ),
        migrations.CreateModel(
            name='Interiorismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre de la exhibición', max_length=100, verbose_name='Nombre de la exhibición')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripción de la exhibición', null=True, verbose_name='Descripción de la exhibición')),
                ('Fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de registro', verbose_name='Fecha de registro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interiorismo_registrado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='Interiorismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portal.interiorismo'),
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre del producto', max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripción del producto', null=True, verbose_name='Descripción del producto')),
                ('Categoria', models.CharField(choices=[('mesa', 'Mesas'), ('silla_banco', 'Sillas y bancos'), ('banca', 'Bancas'), ('sofa', 'Sofás'), ('otoman', 'Otomanes'), ('credenza', 'Credenzas'), ('cantina', 'Cantinas'), ('vitrina', 'Vitrinas'), ('cabecera_cama', 'Cabeceras de cama'), ('escritorio', 'Escritorios')], help_text='Categoría de producto', max_length=50, verbose_name='Categoría de producto')),
                ('Autor', models.CharField(help_text='Autor o fabricante del producto', max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=8)),
                ('Disponible', models.BooleanField(blank=True, default=True, help_text='Disponible')),
                ('Fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de registro por usuario', verbose_name='Fecha de registro por usuario')),
                ('Fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muebles_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='Mueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portal.mueble'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
