# Generated by Django 6.0 on 2026-08-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_foto_producto_exhibicion_registrado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mueble',
            old_name='registrado_por',
            new_name='Registrado_por',
        ),
        migrations.RemoveField(
            model_name='arte',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='decoracion',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='exhibicion',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='interiorismo',
            name='registrado_por',
        ),
        migrations.AlterField(
            model_name='arte',
            name='Categoria',
            field=models.CharField(choices=[('pintura', 'Pinturas'), ('escultura', 'Escultura'), ('fotografia', 'Fotografía'), ('arte_autoctono', 'Arte autóctono')], help_text='Categoría de arte', max_length=50, verbose_name='Categoría de arte'),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='Autor',
            field=models.CharField(help_text='Autor o fabricante del accesorio', max_length=100),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='Categoria',
            field=models.CharField(choices=[('espejo', 'espejos'), ('lampara', 'lámparas'), ('metalisteria', 'Metalistería'), ('acabado_antique', 'Acabado antique'), ('vidrio_ceramica', 'Vidrio y cerámica'), ('tapete', 'Tapetes'), ('cojin', 'Cojines'), ('madera_tallada', 'Madera tallada (ebanistería)')], help_text='Categoría de accesorio', max_length=50, verbose_name='Categoría de accesorio'),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='Descripcion',
            field=models.TextField(blank=True, help_text='Descripción del accesorio', null=True, verbose_name='Descripción del accesorio'),
        ),
        migrations.AlterField(
            model_name='decoracion',
            name='Nombre',
            field=models.CharField(help_text='Nombre del accesorio', max_length=100, unique=True, verbose_name='Nombre del accesorio'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='Autor',
            field=models.CharField(help_text='Autor o fabricante del mueble', max_length=100),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='Categoria',
            field=models.CharField(choices=[('mesa', 'Mesas'), ('silla_banco', 'Sillas y bancos'), ('banca', 'Bancas'), ('sofa', 'Sofás'), ('otoman', 'Otomanes'), ('credenza', 'Credenzas'), ('cantina', 'Cantinas'), ('vitrina', 'Vitrinas'), ('cabecera_cama', 'Cabeceras de cama'), ('escritorio', 'Escritorios')], help_text='Categoría de mueble', max_length=50, verbose_name='Categoría de mueble'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='Descripcion',
            field=models.TextField(blank=True, help_text='Descripción del mueble', null=True, verbose_name='Descripción del mueble'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='Nombre',
            field=models.CharField(help_text='Nombre del mueble', max_length=100, unique=True, verbose_name='Nombre del mueble'),
        ),
        migrations.AddField(
            model_name='arte',
            name='Registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arte_registrado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decoracion',
            name='Registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_decoracion_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibicion',
            name='Registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibiciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='Registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interiorismo',
            name='Registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interiorismo_registrado', to=settings.AUTH_USER_MODEL),
        ),
    ]
