# Generated by Django 6.0 on 2026-09-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_registrado_por_mueble_registrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibicion',
            name='Autor',
            field=models.CharField(default='mayab', help_text='Autor de la obra exhibida', max_length=100),
            preserve_default=False,
        ),
    ]
