"""
Django settings for mayab project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# environment mode (development or production)
ENVIRONMENT_MODE = config('ENVIRONMENT_MODE')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if ENVIRONMENT_MODE == "development" else False 

if ENVIRONMENT_MODE == 'production':
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
elif ENVIRONMENT_MODE == 'development':
    ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    cast=Csv()
)

# Application definition

INSTALLED_APPS = [
    'apps.portal.adminconfig.PortalAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # whitenoise helper for static files in production mode
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if ENVIRONMENT_MODE == 'production':
    DATABASES = {
            'default': {
                'ENGINE': config('ENGINE_DB'),
                'NAME': config('NAME_DB'),
                'USER': config('USER_DB'),
                'PASSWORD':  config('PASSWORD_DB'),
                'HOST': config('HOST_DB'), 
                'PORT': config('PORT_DB'),
            }
        }
    CONN_MAX_AGE = 600 # 600 seconds 
    CONN_HEALTH_CHECKS = True
    
else:  
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = "America/Mexico_City"
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR/'static']
STATIC_ROOT = BASE_DIR/'staticfiles'

# Media files (uploaded images, pdfs, etc)

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"

# mail configurations

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# tasks configuration

TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate."
                   "ImmediateBackend"
    }
}

# Custom backends
AUTHENTICATION_BACKENDS = [
    "config.backends.EmailBackend",
]

# HTTPS 
CSRF_COOKIE_SECURE = True if ENVIRONMENT_MODE == 'production' else False
SESSION_COOKIE_SECURE = True if ENVIRONMENT_MODE == 'production' else False
SECURE_SSL_REDIRECT  = True if ENVIRONMENT_MODE == 'production' else False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# admins to contact in case of a 500 error
ADMINS = [
    ("Salvador", "salvador.garcilita@bioalgoritmia.com"),
]
# managers to contact in case of a broken link
MANAGERS = [
    ("Salvador", "salvador.garcilita@bioalgoritmia.com"),
]